enum DutyPosition {
  DRIVER = 'DRIVER',
  LEADER = 'LEADER',
  RESCUER = 'RESCUER',
  RADIO_OPERATOR = 'RADIO_OPERATOR',
  ASSISTANT_RADIO_OPERATOR = 'ASSISTANT_RADIO_OPERATOR',
  TRAINEE = 'TRAINEE',
}

export default DutyPosition;
