enum Position {
  DRIVER = 'DRIVER',
  LEADER = 'LEADER',
  LEADER_TRAINEE = 'LEADER_TRAINEE',
  FIRST_RESCUER = 'FIRST_RESCUER',
  SECOND_RESCUER = 'SECOND_RESCUER',
  RADIO_OPERATOR = 'RADIO_OPERATOR',
  RADIO_OPERATOR_ASSISTANT = 'RADIO_OPERATOR_ASSISTANT',
  TRAINEE = 'TRAINEE',
}

export default Position;
